// <auto-generated />
using System;
using BackendExercise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendExercise.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20220216133200_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackendExercise.Models.Person", b =>
                {
                    b.Property<int>("IDnr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDnr"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonIDnr")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("IDnr");

                    b.HasIndex("PersonIDnr");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("BackendExercise.Models.Person", b =>
                {
                    b.HasOne("BackendExercise.Models.Person", null)
                        .WithMany("OtherPersons")
                        .HasForeignKey("PersonIDnr");
                });

            modelBuilder.Entity("BackendExercise.Models.Person", b =>
                {
                    b.Navigation("OtherPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
